package requests

type Header struct {
	ExchangedDeliveryNoticeDocumentIdentifier                      string   `json:"ExchangedDeliveryNoticeDocumentIdentifier"`
	DeliveryNoticeDocument                                         *string  `json:"DeliveryNoticeDocument"`
	ExchangedDocumentContextSpecifiedTransactionIdentifier         *string  `json:"ExchangedDocumentContextSpecifiedTransactionIdentifier"`
	ExchangedDeliveryNoticeDocumentName                            *string  `json:"ExchangedDeliveryNoticeDocumentName"`
	ExchangeDeliveryNoticeDocumentTypeCode                         *string  `json:"ExchangeDeliveryNoticeDocumentTypeCode"`
	ExchangedDeliveryNoticeDocumentIssueDate                       *string  `json:"ExchangedDeliveryNoticeDocumentIssueDate"`
	ExchangedDeliveryNoticeDocumentPurposeCode                     *string  `json:"ExchangedDeliveryNoticeDocumentPurposeCode"`
	ExchangedDeliveryNoticeDocumentRequestedResponseTypeCode       *string  `json:"ExchangedDeliveryNoticeDocumentRequestedResponseTypeCode"`
	ExchangedDeliveryNoticeDocumentVersionIdentifier               *string  `json:"ExchangedDeliveryNoticeDocumentVersionIdentifier"`
	ExchangedDeliveryNoticeDocumentCategoryCode                    *string  `json:"ExchangedDeliveryNoticeDocumentCategoryCode"`
	ExchangedDeliveryNoticeDocumentSubtypeCode                     *string  `json:"ExchangedDeliveryNoticeDocumentSubtypeCode"`
	NoteDeliveryNoticeSubjectText                                  *string  `json:"NoteDeliveryNoticeSubjectText"`
	NoteDeliveryNoticeContentText                                  *string  `json:"NoteDeliveryNoticeContentText"`
	NoteDeliveryNoticeIdentifier                                   *string  `json:"NoteDeliveryNoticeIdentifier"`
	SpecifiedBinaryFileIdentifier                                  *string  `json:"SpecifiedBinaryFileIdentifier"`
	SpecifiedBinaryFileVersionIdentifier                           *string  `json:"SpecifiedBinaryFileVersionIdentifier"`
	SpecifiedBinaryFileNameText                                    *string  `json:"SpecifiedBinaryFileNameText"`
	SpecifiedBineryFileURIIdentifier                               *string  `json:"SpecifiedBineryFileURIIdentifier"`
	SpecifiedBineryFileMIMECode                                    *string  `json:"SpecifiedBineryFileMIMECode"`
	SpecifiedBineryFileEncodingCode                                *string  `json:"SpecifiedBineryFileEncodingCode"`
	SpecifiedBineryFileCode                                        *string  `json:"SpecifiedBineryFileCode"`
	SpecifiedBinaryFileDescriptionText                             *string  `json:"SpecifiedBinaryFileDescriptionText"`
	TradeSellerIdentifier                                          *string  `json:"TradeSellerIdentifier"`
	TradeSellerGlobalIdentifier                                    *string  `json:"TradeSellerGlobalIdentifier"`
	TradeSellerName                                                *string  `json:"TradeSellerName"`
	TradeBillFromPartyRegisteredIdentifier                         *string  `json:"TradeBillFromPartyRegisteredIdentifier"`
	TradeContactSellerIdentifier                                   *string  `json:"TradeContactSellerIdentifier"`
	TradeContactSellerPersonName                                   *string  `json:"TradeContactSellerPersonName"`
	TradeContactSellerDepartmentName                               *string  `json:"TradeContactSellerDepartmentName"`
	SellerTelephoneNumber                                          *string  `json:"SellerTelephoneNumber"`
	SellerFaxNumber                                                *string  `json:"SellerFaxNumber"`
	SellerEmailAddress                                             *string  `json:"SellerEmailAddress"`
	SellerAddressPostalCode                                        *string  `json:"SellerAddressPostalCode"`
	SellerAddress                                                  *string  `json:"SellerAddress"`
	TradeBuyerIdentifier                                           *string  `json:"TradeBuyerIdentifier"`
	TradeBuyerGlobalIdentifier                                     *string  `json:"TradeBuyerGlobalIdentifier"`
	TradeBuyerName                                                 *string  `json:"TradeBuyerName"`
	TradeContactBuyerIdentifier                                    *string  `json:"TradeContactBuyerIdentifier"`
	TradeContactBuyerPersonName                                    *string  `json:"TradeContactBuyerPersonName"`
	TradeContactBuyerDepartmentName                                *string  `json:"TradeContactBuyerDepartmentName"`
	BuyerTelephoneNumber                                           *string  `json:"BuyerTelephoneNumber"`
	BuyerFaxNumber                                                 *string  `json:"BuyerFaxNumber"`
	BuyerEmailAddress                                              *string  `json:"BuyerEmailAddress"`
	BuyerAddressPostalCode                                         *string  `json:"BuyerAddressPostalCode"`
	BuyerAddress                                                   *string  `json:"BuyerAddress"`
	ReferencedOrdersDocumentIssureAssignedIdentifier               *string  `json:"ReferencedOrdersDocumentIssureAssignedIdentifier"`
	ReferencedOrdersDocumentIssueDate                              *string  `json:"ReferencedOrdersDocumentIssueDate"`
	ReferencedOrdersDocumentRevisionIdentifier                     *string  `json:"ReferencedOrdersDocumentRevisionIdentifier"`
	ReferencedOrdersDocumentName                                   *string  `json:"ReferencedOrdersDocumentName"`
	ReferencedOrdersDocumentInformationText                        *string  `json:"ReferencedOrdersDocumentInformationText"`
	ReferencedOrdersDocumentInformationPurposeCode                 *string  `json:"ReferencedOrdersDocumentInformationPurposeCode"`
	ReferencedOrdersDocumentInformationSubtypeCode                 *string  `json:"ReferencedOrdersDocumentInformationSubtypeCode"`
	ProjectIdentifier                                              *string  `json:"ProjectIdentifier"`
	ProjectName                                                    *string  `json:"ProjectName"`
	ReferencedSalesOrderDocumentIssureAddignedIdentifier           *string  `json:"ReferencedSalesOrderDocumentIssureAddignedIdentifier"`
	ReferencedSalesOrderDocumentIssueDate                          *string  `json:"ReferencedSalesOrderDocumentIssueDate"`
	ReferencedSalesOrderDocumentRevisionIdentifier                 *string  `json:"ReferencedSalesOrderDocumentRevisionIdentifier"`
	ReferencedSalesOrderDocumentName                               *string  `json:"ReferencedSalesOrderDocumentName"`
	ReferencedSalesOrderDocumentInformationText                    *string  `json:"ReferencedSalesOrderDocumentInformationText"`
	ReferencedSalesOrderDocumentSubtypeCode                        *string  `json:"ReferencedSalesOrderDocumentSubtypeCode"`
	TradeShipToPartyIdentifier                                     *string  `json:"TradeShipToPartyIdentifier"`
	TradeShipToPartyGlobalIdentifier                               *string  `json:"TradeShipToPartyGlobalIdentifier"`
	TradeShipToPartyName                                           *string  `json:"TradeShipToPartyName"`
	TradeShipToPartyContactIdentifier                              *string  `json:"TradeShipToPartyContactIdentifier"`
	TradeShipToPartyContactPersonName                              *string  `json:"TradeShipToPartyContactPersonName"`
	TradeShipToPartyContactDepartmentName                          *string  `json:"TradeShipToPartyContactDepartmentName"`
	TradeShipToPartyContactPersonIdentifier                        *string  `json:"TradeShipToPartyContactPersonIdentifier"`
	ShipToPartyTelephoneNumber                                     *string  `json:"ShipToPartyTelephoneNumber"`
	ShipToPartyFaxNumber                                           *string  `json:"ShipToPartyFaxNumber"`
	ShipToPartyEmailAddress                                        *string  `json:"ShipToPartyEmailAddress"`
	ShipToPartyAddressPostalCode                                   *string  `json:"ShipToPartyAddressPostalCode"`
	ShipToPartyAddress                                             *string  `json:"ShipToPartyAddress"`
	TradeShipFromPartyIdentifier                                   *string  `json:"TradeShipFromPartyIdentifier"`
	TradeShipFromPartyName                                         *string  `json:"TradeShipFromPartyName"`
	TradeLogiName                                                  *string  `json:"TradeLogiName"`
	TradeLogiContactIdentifier                                     *string  `json:"TradeLogiContactIdentifier"`
	TradeLogiContactPersonName                                     *string  `json:"TradeLogiContactPersonName"`
	TradeLogiContactDepartmentName                                 *string  `json:"TradeLogiContactDepartmentName"`
	TradeLogiContactPersonIdentifier                               *string  `json:"TradeLogiContactPersonIdentifier"`
	LogiTelephoneNumber                                            *string  `json:"LogiTelephoneNumber"`
	SupplyChainEventIdentifier                                     *string  `json:"SupplyChainEventIdentifier"`
	InstructedTemperatureControlCode                               *string  `json:"InstructedTemperatureControlCode"`
	TradeTaxCalculatedAmount                                       *float32 `json:"TradeTaxCalculatedAmount"`
	TradeTaxTypeCode                                               *string  `json:"TradeTaxTypeCode"`
	TradeTaxBasisAmount                                            *float32 `json:"TradeTaxBasisAmount"`
	TradeTaxCategoryCode                                           *string  `json:"TradeTaxCategoryCode"`
	TradeTaxCategoryName                                           *string  `json:"TradeTaxCategoryName"`
	TradeTaxRatePercent                                            *float32 `json:"TradeTaxRatePercent"`
	TradeTaxGrandTotalAmount                                       *float32 `json:"TradeTaxGrandTotalAmount"`
	TradeTaxCalculationMethod                                      *string  `json:"TradeTaxCalculationMethod"`
	TradeSettlementMonetarySummationTotalTaxAmount                 *float32 `json:"TradeSettlementMonetarySummationTotalTaxAmount"`
	TradeDeliveryNoticeSettlementMonetarySummationGrandTotalAmount *float32 `json:"TradeDeliveryNoticeSettlementMonetarySummationGrandTotalAmount"`
	TradeDeliveryNoticeSettlementMonetarySummationNetTotalAmount   *float32 `json:"TradeDeliveryNoticeSettlementMonetarySummationNetTotalAmount"`
	TradeDeliveryNoticeMonetarySummationIncludingTaxesTotalAmount  *float32 `json:"TradeDeliveryNoticeMonetarySummationIncludingTaxesTotalAmount"`
}
