package requests

type Item struct {
	ExchangedDeliveryNoticeDocumentIdentifier                                      string   `json:"ExchangedDeliveryNoticeDocumentIdentifier"`
	DeliveryNoticeDocumentItemlineIdentifier                                       string   `json:"DeliveryNoticeDocumentItemlineIdentifier"`
	DeliveryNoticeDocumentItemlineStatusCode                                       *string  `json:"DeliveryNoticeDocumentItemlineStatusCode"`
	DeliveryNoticeDocumentItemlineStatusReasonCode                                 *string  `json:"DeliveryNoticeDocumentItemlineStatusReasonCode"`
	NoteDeliveryNoticeItemSubjectText                                              *string  `json:"NoteDeliveryNoticeItemSubjectText"`
	NoteDeliveryNoticeItemContentText                                              *string  `json:"NoteDeliveryNoticeItemContentText"`
	NoteDeliveryNoticeItemIdentifier                                               *string  `json:"NoteDeliveryNoticeItemIdentifier"`
	ReferencedSalesOrderDocumentIssuerAssignedIdentifier                           *string  `json:"ReferencedSalesOrderDocumentIssuerAssignedIdentifier"`
	ReferencedSalesOrderDocumentItemLineIdentifier                                 *string  `json:"ReferencedSalesOrderDocumentItemLineIdentifier"`
	ReferencedSalesOrderDocumentRevisionIdentifier                                 *string  `json:"ReferencedSalesOrderDocumentRevisionIdentifier"`
	ReferencedOrdersDocumentIssureAssignedIdentifier                               *string  `json:"ReferencedOrdersDocumentIssureAssignedIdentifier"`
	ReferencedOrdersDocumentItemLineIdentifier                                     *string  `json:"ReferencedOrdersDocumentItemLineIdentifier"`
	ReferencedOrdersDocumentRevisionIdentifier                                     *string  `json:"ReferencedOrdersDocumentRevisionIdentifier"`
	TradePriceTypeCode                                                             *string  `json:"TradePriceTypeCode"`
	TradeDeliveryPriceChargeAmount                                                 *float32 `json:"TradeDeliveryPriceChargeAmount"`
	TradePriceBasisQuantity                                                        *float32 `json:"TradePriceBasisQuantity"`
	TradePriceBasisUnitCode                                                        *string  `json:"TradePriceBasisUnitCode"`
	SupplyChainTradeDeliveryPackageQuantity                                        *float32 `json:"SupplyChainTradeDeliveryPackageQuantity"`
	SupplyChainTradeDeliveryProductUnitQuantity                                    *float32 `json:"SupplyChainTradeDeliveryProductUnitQuantity"`
	SupplyChainTradeDeliveryPerPackageUnitQuantity                                 *float32 `json:"SupplyChainTradeDeliveryPerPackageUnitQuantity"`
	SupplyChainTradeDeliveryDespatchedQuantity                                     *float32 `json:"SupplyChainTradeDeliveryDespatchedQuantity"`
	SupplyChainTradeDeliveryRequestedQuantity                                      *float32 `json:"SupplyChainTradeDeliveryRequestedQuantity"`
	SupplyChainTradeDeliveryRemainingRequestedQuantity                             *float32 `json:"SupplyChainTradeDeliveryRemainingRequestedQuantity"`
	ItemTradeDeliverToPartyIdentifier                                              *string  `json:"ItemTradeDeliverToPartyIdentifier"`
	ItemTradeDeliverToPartyGlobalIdentifier                                        *string  `json:"ItemTradeDeliverToPartyGlobalIdentifier"`
	ItemTradeDeliverToPartyName                                                    *string  `json:"ItemTradeDeliverToPartyName"`
	ItemTradeDeliverToPartyContactPersonName                                       *string  `json:"ItemTradeDeliverToPartyContactPersonName"`
	ItemTradeDeliverToPartyContactDepartmentName                                   *string  `json:"ItemTradeDeliverToPartyContactDepartmentName"`
	ItemDeliverToPartyPhoneNumber                                                  *string  `json:"ItemDeliverToPartyPhoneNumber"`
	ItemDeliverToPartyFaxNumber                                                    *string  `json:"ItemDeliverToPartyFaxNumber"`
	ItemDeliverToPartyEMailAddress                                                 *string  `json:"ItemDeliverToPartyEMailAddress"`
	ItemDeliverToPartyAddressPostalCode                                            *string  `json:"ItemDeliverToPartyAddressPostalCode"`
	ItemDeliverToPartyAddress                                                      *string  `json:"ItemDeliverToPartyAddress"`
	SupplyChainDeliveryEventIdentifier                                             *string  `json:"SupplyChainDeliveryEventIdentifier"`
	SupplyChainDeliveryEventOccurrenceDate                                         *string  `json:"SupplyChainDeliveryEventOccurrenceDate"`
	SupplyChainEventTypeCode                                                       *string  `json:"SupplyChainEventTypeCode"`
	SupplyChainEventRequirementOccurrenceDate                                      *string  `json:"SupplyChainEventRequirementOccurrenceDate"`
	LogisticsLocationIdentification                                                *string  `json:"LogisticsLocationIdentification"`
	LogisticsLocationName                                                          *string  `json:"LogisticsLocationName"`
	SupplyChainEventPlannedOccurrenceDate                                          *string  `json:"SupplyChainEventPlannedOccurrenceDate"`
	TradeTaxTypeCode                                                               *string  `json:"TradeTaxTypeCode"`
	ItemTradeTaxBasisAmount                                                        *float32 `json:"ItemTradeTaxBasisAmount"`
	ItemTradeTaxCategoryCode                                                       *string  `json:"ItemTradeTaxCategoryCode"`
	TradeTaxCategoryName                                                           *string  `json:"TradeTaxCategoryName"`
	ItemTradeTaxRateApplicablePercent                                              *float32 `json:"ItemTradeTaxRateApplicablePercent"`
	ItemTradeTaxGrandTotalAmount                                                   *float32 `json:"ItemTradeTaxGrandTotalAmount"`
	ItemTradeDeliveryNoticeSettlementMonetarySummationNetTotalAmount               *float32 `json:"ItemTradeDeliveryNoticeSettlementMonetarySummationNetTotalAmount"`
	ItemTradeDeliveryNoticeSettlementMonetarySummationIncludingTaxesNetTotalAmount *float32 `json:"ItemTradeDeliveryNoticeSettlementMonetarySummationIncludingTaxesNetTotalAmount"`
	TradeProductIdentifier                                                         *string  `json:"TradeProductIdentifier"`
	TradeProductGlobalIdentifier                                                   *string  `json:"TradeProductGlobalIdentifier"`
	TradeProductSellerAssignedIdentifier                                           *string  `json:"TradeProductSellerAssignedIdentifier"`
	TradeProductBuyerAssignedIdentifier                                            *string  `json:"TradeProductBuyerAssignedIdentifier"`
	TradeProductManufacturerAssignedIdentifier                                     *string  `json:"TradeProductManufacturerAssignedIdentifier"`
	TradeProductName                                                               *string  `json:"TradeProductName"`
	TradeProductDescription                                                        *string  `json:"TradeProductDescription"`
	TradeProductTypeCode                                                           *string  `json:"TradeProductTypeCode"`
	TradeProductEndItemTypeCode                                                    *string  `json:"TradeProductEndItemTypeCode"`
	TradeProductSizeCode                                                           *string  `json:"TradeProductSizeCode"`
	TradeProductSizeDescriptionText                                                *string  `json:"TradeProductSizeDescriptionText"`
	TradeManufacturerIdentifier                                                    *string  `json:"TradeManufacturerIdentifier"`
	TradeManufacturerName                                                          *string  `json:"TradeManufacturerName"`
	ReferencedLogisticsPackageUnitQuantity                                         *float32 `json:"ReferencedLogisticsPackageUnitQuantity"`
	ReferencedLogisticsPackageQuantityUnitCode                                     *string  `json:"ReferencedLogisticsPackageQuantityUnitCode"`
	ReferencedLogisticsPackageTypeCode                                             *string  `json:"ReferencedLogisticsPackageTypeCode"`
	ReferencedLogisticsPackageIdentifier                                           *string  `json:"ReferencedLogisticsPackageIdentifier"`
}
